# Generated by Django 4.2 on 2023-04-23 08:41

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
        migrations.CreateModel(
            name='TrackingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos_tracking', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('date_time', models.DateField(default=datetime.datetime.now)),
                ('date_time_modify', models.DateTimeField(auto_now=True)),
                ('date_time_upload', models.DateTimeField(auto_now_add=True)),
                ('video_result_file', models.FileField(null=True, upload_to='videos_tracking/object_tracking/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('counting_result_file', models.FileField(null=True, upload_to='videos_tracking/object_tracking/')),
                ('OriginalVideo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.originalvideo')),
                ('TrackingVideo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.trackingvideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_name', models.CharField(max_length=255)),
                ('loop_id', models.IntegerField()),
                ('orientation', models.CharField(max_length=255)),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('x2', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('x3', models.IntegerField()),
                ('y3', models.IntegerField()),
                ('x4', models.IntegerField()),
                ('y4', models.IntegerField()),
                ('summary_location_x', models.IntegerField()),
                ('summary_location_y', models.IntegerField()),
                ('head_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
