# Generated by Django 4.2 on 2023-04-21 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoopWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop1', to='tasks.loop')),
                ('loop2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop2', to='tasks.loop')),
                ('loop3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop3', to='tasks.loop')),
                ('loop4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop4', to='tasks.loop')),
            ],
        ),
    ]
