# Generated by Django 4.2 on 2023-04-22 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_trackingvideo_loop_trackingvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='originalVideo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.originalvideo'),
        ),
    ]
